// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsPM11l21qBJETaMbxVW4g0SZwRh0CFIk',
    appId: '1:447494317792:web:434b30d21ff05dc7b95285',
    messagingSenderId: '447494317792',
    projectId: 'tl-le-hub',
    authDomain: 'tl-le-hub.firebaseapp.com',
    storageBucket: 'tl-le-hub.firebasestorage.app',
    measurementId: 'G-SEHWSXWPE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAda6f6zH_xph2bmg3vu7XZic-4x_rg08I',
    appId: '1:447494317792:android:d9c79d5414c24fe2b95285',
    messagingSenderId: '447494317792',
    projectId: 'tl-le-hub',
    storageBucket: 'tl-le-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf2dc0noGK0pYqGbRQpWSkgg_AUMWaP8Y',
    appId: '1:447494317792:ios:0da21c13c48e220fb95285',
    messagingSenderId: '447494317792',
    projectId: 'tl-le-hub',
    storageBucket: 'tl-le-hub.firebasestorage.app',
    iosBundleId: 'com.technolenz.lehub',
  );
}
